apiVersion: apps/v1

kind: Deployment

metadata:

  name: cyberexpert-deployment

  labels:

    app: cyberexpert

spec:

  replicas: 1

  selector:

    matchLabels:

      app: cyberexpert

  template:

    metadata:

      labels:

        app: cyberexpert

    spec:

      containers:

      - name: cyberexpert-server

        image: nethrashreec/myapp1

        ports:

        - containerPort: 80

