apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberexpert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberexpert
  template:
    metadata:
      labels:
        app: cyberexpert
    spec:
      containers:
      - name: cyberexpert
        image: nethrashreec/myapp1:latest
        ports:
        - containerPort: 8000
