apiVersion: v1
kind: Pod
metadata:
   name: nodeapp
   labels:
     app: nodeapp
spec:
   containers:
   - name: nodeapp
     image: nethrashreec/myapp1:v1
     ports:
     - containerPort: 8080





apiVersion: v1
kind: Service
metadata:
  name: cyberexpert-service
spec:
  selector:
    app: cyberexpert
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000
  type: LoadBalancer
