apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberexpert-deployment
  labels:
    app: cyberexpert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberexpert
  template:
    metadata:
      labels:
        app: cyberexpert
    spec:
      containers:
      - name: cyberexpert-server
        image: nethrashreec/myapp1
        ports:
        - containerPort: 80
       
 
apiVersion: v1
kind: Pod
metadata: 
  name: cyberexpert
  labels:
    app: cyberexpert
spec:
  containers:
  - name: cyberexpert
  image: nethrashreec/myapp1:v1
  ports:
  - containerPort: 8080



apiVersion: v1
kind: Service
metadata:
  name: cyberexpert-service
spec:
  selector:
    app: cyberexpert
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000
  type: LoadBalancer
