apiVersion: apps/v1

kind: Deployment

metadata:

  name: cyberexpert-deployment

spec:

  selector:

    matchLabels:

      app: cyberexpert

  replicas: 1

  template:

    metadata:

      labels:

        app: cyberexpert

    spec:

      containers:

      - name: cyber

        image: nethrashreec/myapp1

        resources:

          limits:

            memory: "140Mi"

            cpu: "400m"

        ports:

        - containerPort: 80




apiVersion: v1
kind: Service
metadata:
  name: cyberexpert-service
spec:
  selector:
    app: cyberexpert
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000
  type: LoadBalancer
